# Generated by Django 2.2 on 2019-05-08 14:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190419_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demander',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('father_id', models.IntegerField(verbose_name='father_id')),
                ('father_detail_id', models.IntegerField(verbose_name='father_detail_id')),
                ('num', models.FloatField(verbose_name='num')),
                ('price', models.FloatField(verbose_name='price')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('form_type', models.IntegerField(verbose_name='form_type')),
                ('form_id', models.IntegerField(verbose_name='form_id')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('due_time', models.DateTimeField(verbose_name='due_time')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_time')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('check_time', models.DateTimeField(verbose_name='check_time')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('demander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.Demander')),
            ],
        ),
    ]
