# Generated by Django 2.2 on 2019-05-09 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demander_Demand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('num', models.FloatField(verbose_name='num')),
                ('demander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.Demander')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.Medicine')),
            ],
        ),
    ]
