# Generated by Django 2.2 on 2019-05-09 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_remove_demander_demand_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='check_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check_time'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='due_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='due_time'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='father_detail_id',
            field=models.IntegerField(default=0, verbose_name='father_detail_id'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='father_id',
            field=models.IntegerField(default=0, verbose_name='father_id'),
        ),
    ]
