# Generated by Django 2.2 on 2019-05-17 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0006_auto_20190510_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_time'),
        ),
    ]
